language: php

php:
  - 5.4
  - 5.5

before_script: ./scripts/travis_before_script.sh

env:
  - DB=mysql
# dregad 20130714 PostgreSQL builds disabled temporarily (until #14398 is fixed)
#  - DB=pgsql

script: phpunit --bootstrap ./tests/bootstrap.php ./tests/AllTests.php

notifications:
  irc: "chat.freenode.net#mantisbt-help"
